[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules','lib']
test = 'test/foundry'
cache_path = 'forge_cache'
optimizer = true
optimizer_runs = 200
via_ir = true
solc_version = "0.8.26"
